jellyshot: move cmds/assignments into sections

diff --git a/jellyshot b/jellyshot
--- a/jellyshot
+++ b/jellyshot
@@ -4,28 +4,24 @@
 set -E -o pipefail
 
 # Traps for cleanup
-trap '{ [[ -f "$file" ]] && rm -v "$file"; }' EXIT
-trap '{ [[ -f "$file" ]] && rm -v "$file"; exit 1; }' ERR
-trap '{ [[ -f "$file" ]] && rm -v "$file"; trap - INT; kill -INT $$; }' INT
+trap '{ cleanup; }' EXIT
+trap '{ cleanup; exit 1; }' ERR
+trap '{ cleanup; trap - INT; kill -INT $$; }' INT
 
-function rand_element () {
-  if [[ "$#" -le 1 ]]; then
-    printf "%s\n" "No array passed to rand_element()"
-    exit 1
-  else
-    eval printf "%s" "\${$((RANDOM % ${#}))}"
+function cleanup() {
+  if [[ -f "$file" ]]; then
+    echo
+    rm -v "$file"
   fi
 }
 
-config="${XDG_CONFIG_HOME:-${HOME}/.config}/jellyshot/config"
-
-if [[ -f "$config" ]]; then
-  # shellcheck disable=SC1090
-  . "$config"
-else
-  printf "%s: %s\n" "No configuration available at" "$config"
-  exit 1
-fi
+function rand_element() {
+  if [[ "$#" -le 1 ]]; then
+    printf "%s\n" "No array passed to rand_element()"
+    exit 1
+  fi
+  eval printf '%s' "\${$((RANDOM % ${#}))}"
+}
 
 ANIMALS=(Aardvark Albatross Alligator Alpaca Ant Anteater Antelope Ape Armadillo Baboon Badger Barracuda Bat Bear Beaver Bee Bison Boar Buffalo Galago Butterfly Camel Caribou Cat Caterpillar Cattle Chamois Cheetah Chicken Chimpanzee Chinchilla Chough Clam Cobra Cockroach Cod Cormorant Coyote Crab Crane Crocodile Crow Curlew Deer Dinosaur Dog Dogfish Dolphin Donkey Dotterel Dove Dragonfly Duck Dugong Dunlin Eagle Echidna Eel Eland Elephant Elephant seal Elk Emu Falcon Ferret Finch Fish Flamingo Fly Fox Frog Gaur Gazelle Gerbil Giant Panda Giraffe Gnat Gnu Goat Goose Goldfinch Goldfish Gorilla Goshawk Grasshopper Grouse Guanaco Guinea fowl Guinea pig Gull Hamster Hare Hawk Hedgehog Heron Herring Hippopotamus Hornet Horse Human Hummingbird Hyena Jackal Jaguar Jay Jellyfish Kangaroo Koala Komodo dragon Kouprey Kudu Lapwing Lark Lemur Leopard Lion Llama Lobster Locust Loris Louse Lyrebird Magpie Mallard Manatee Marten Meerkat Mink Mole Monkey Moose Mouse Mosquito Mule Narwhal Newt Nightingale Octopus Okapi Opossum Oryx Ostrich Otter Owl Ox Oyster Panther Parrot Partridge Peafowl Pelican Penguin Pheasant Pig Pigeon Pony Porcupine Porpoise Prairie Dog Quail Quelea Rabbit Raccoon Rail Ram Rat Raven Red deer Red panda Reindeer Rhinoceros Rook Ruff Salamander Salmon Sandpiper Sardine Scorpion Sea lion Sea Urchin Seahorse Seal Shark Sheep Shrew Shrimp Skunk Snail Snake Spider Squid Squirrel Starling Stingray Stinkbug Stork Swallow Swan Tapir Tarsier Termite Tiger Toad Trout Turkey Turtle Vicuña Viper Vulture Wallaby Walrus Wasp Water buffalo Weasel Whale Wolf Wolverine Wombat Woodcock Woodpecker Worm Wren Yak Zebra)
 COLORS=(Red Blue Green Cyan Blue Purple Yellow Lime Magenta Green Orange Brown Maroon Black Silver White)
@@ -36,14 +32,23 @@ colors="$(rand_element "${COLORS[@]}")"
 animals="$(rand_element "${ANIMALS[@]}")"
 
 name="${vowels}${colors}${animals}.png"
-file="/tmp/$name"
+file="/tmp/${name}"
+config="${XDG_CONFIG_HOME:-${HOME}/.config}/jellyshot/config"
 
-if type import &>/dev/null; then
-  import "$file"
-else
-  printf "%s\n" "'import' not found in \$PATH"
+if [[ ! -f "$config" ]]; then
+  printf "%s: %s\n" "No configuration available at" "$config"
   exit 1
 fi
+
+# shellcheck disable=SC1090
+. "$config"
+
+if ! type import &>/dev/null; then
+  printf "%s\n" "'import' not found in \$PATH"
+  exit 127
+fi
+
+import "$file"
 
 if type optipng &>/dev/null; then
   optipng "$file" &>/dev/null
@@ -51,8 +56,10 @@ fi
 
 # Add single / prefix if SUFFIX is set
 case "$SUFFIX" in
-  (/*) SUFFIX="/${SUFFIX//\/}" ;;
-  (?*) SUFFIX="/${SUFFIX%/*}" ;;
+(/*)
+  SUFFIX="/${SUFFIX//\/}" ;;
+(?*)
+  SUFFIX="/${SUFFIX%/*}" ;;
 esac
 
 if [[ -z "$SERVER_PATH" ]]; then
