Add cleanup traps and XDG_CONFIG_HOME

diff --git a/jellyshot b/jellyshot
--- a/jellyshot
+++ b/jellyshot
@@ -1,13 +1,25 @@
 #!/bin/bash
 
-# XXX: XDG_CONFIG_HOME
-config="${HOME}/.config/jellyshot/config"
+# Let trap catch non-zero exit status
+set -E -o pipefail
 
-if [[ -f ${config} ]];
-then
-  . "${config}"
+# Traps for cleanup
+trap '{ [[ -f "$file" ]] && rm -v "$file"; }' EXIT
+trap '{ [[ -f "$file" ]] && rm -v "$file"; exit 1; }' ERR
+trap '{ [[ -f "$file" ]] && rm -v "$file"; trap - INT; kill -INT $$; }' INT
+
+function rand_element () {
+  local -a arr
+  arr=("${!1}")
+  echo "${arr["$[RANDOM % ${#arr[@]}]"]}"
+}
+
+config="${XDG_CONFIG_HOME:-${HOME}/.config}/jellyshot/config"
+
+if [[ -f "$config" ]]; then
+  . "$config"
 else
-  echo "No configuration available at ${config}"
+  printf "%s: %s\n" "No configuration available at" "$config"
   exit 1
 fi
 
@@ -15,11 +27,6 @@ ANIMALS=(Aardvark Albatross Alligator Alpaca Ant Anteater Antelope Ape Armadillo
 
 COLORS=(Red Blue Green Cyan Blue Purple Yellow Lime Magenta Green Orange Brown Maroon Black Silver White)
 VOWELS=(Amazing Gigantic Enormous Huge Broad Ridiculous Shallow Silent Soft Fluffy Dusty Miniature Chucklesome Absurd Hilarious Droll Amusing Silly Hysterical Humorous Laughable Astounding Astonishing Stunning Bewildering Shocking Startling Breathtaking Disconcerting Fierce Evil Frightened Foolish Creepy Confused Arrogant Ashamed Angry Awful Cheerful Witty Proud Jolly Kind Gentle)
-
-rand_element() {
-  arr=("${!1}"); 
-  echo ${arr["$[RANDOM % ${#arr[@]}]"]};
-}
 
 vowel=$(rand_element "VOWELS[@]")
 color=$(rand_element "COLORS[@]")
@@ -42,6 +49,5 @@ else
 fi
 
 echo $url;
-rm $file # XXX use TRAP
 
 echo "$url" | xclip -i
